server:
  http_listen_port: 3200

search:
  enabled: true

# Ensina o Tempo a abrir os receptores gRPC internos
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
    wal:
      path: /tmp/tempo/wal