server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/products/**

        - id: customer-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - RewritePath=/api/v1/customers(?<segment>/?.*), /api/v1/customers$\{segment}
