version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.13-node
    
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "order-service/pom.xml" }}
            - v1-dependencies-

      - run:
          name: Executando Testes e Compilação dos Microsserviços
          command: |
            echo "Iniciando build do ecossistema..."
            # Executa o comando do Maven silenciando os avisos de agente dinâmico do Java 21
            mvn clean verify -DargLine="-XX:+EnableDynamicAgentLoading"

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "order-service/pom.xml" }}

      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  pipeline-ecommerce:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: 
                - main
                - develop