server:
  port: 8081

spring:
  application:
    name: order-service

  # Desativa o Config Server que conflitava com o Feign antigo
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10000ms
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}